model:
  base_learning_rate: 4.5e-6
  target: taming1.models.emo_feat_space.VQModel
  params:
    emotion_class: 6
    embed_dim: 256
    n_embed: 1024
    ckpt_path: logs/vqgan_landscape_f16_1024.ckpt

    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  #
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: taming1.modules.losses.vqperceptual.VQLPIPSWithDiscriminator #
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 1
    train:
      target: taming1.data.custom.CustomTrain
      params:
        training_images_list_file: datasets/path
        size: 256
    validation:
      target: taming1.data.custom.CustomTest
      params:
        test_images_list_file: datasets/path
        size: 256

